Undefined reference to boost path filename
The linker can't find the boost filename method. The filename
method was used in a helper method but that method was never
called. Got rid of the reference instead of trying to figure out
what changed that boost::filesystem::path::filename doesn't
work with newer boost versions.